### ISSUE TITLE
Cannot register with Github

### ISSUE THREAD

**Issue by YTCuber** [Kannaj/42EXP#34]
I go to https://42exp.com/ and click the button "Register with Github" on the top right. The browser writes "Loading error" and tries to load "http://localhost:8000/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch". "Login with Github" shows the same error.

I am using Firefox 53.0.2 with Ubuntu 17.04.

**Comment by Kannaj** [comment]
This has been fixed now. can you check? there was a mix up of .env files

**Comment by YTCuber** [comment]
Yep, it works now. Thanks for fixing!
